### ISSUE TITLE
Default "schema file" path - `fauna/schema.gql` or `models/schema.gql`

### ISSUE THREAD

**Issue by Vadorequest** [Plazide/fauna-gql-upload#20]
Doc is confusing about this, I guess it's a typo.

> You need a valid schema file to upload. This file should be located at fauna/schema.gql relative to the working directory where the command is executed. This is required

![image](https://user-images.githubusercontent.com/3807458/111817190-000e8180-88de-11eb-8073-b776037a59b6.png)

**Comment by Plazide** [comment]
Yes, that's a typo. The actual default path is `fauna/schema.gql`, but it would also work if you name the file `fauna/schema.graphql`.

Thanks for letting me know, I'll correct this in a little bit.
