### ISSUE TITLE
how can I add password for uploaded data? 

### ISSUE THREAD

**Issue by Yankee-by** [Plazide/fauna-gql-upload#27]
Is it possible to attach password to the data field?
`
export default {
  collection: "Languages",
  index: "languages_by_key",
  key: "key",
  data: [
    { key: "en", name: "English", credentials: {password: "123"} },
  ],
};
`

**Comment by Plazide** [comment]
Not at the moment.

I can definitely see the use of being able to attach a password to your data. The simplest way to implement it would be to add another field for credentials, like:

```js
export default {
  collection: "Langauges",
  index: "languages_by_key",
  key: "key",
  data: [
    {
      key: "en",
      name: "English"
    }
  ],
  credentials: [
    {
      key: "en",
      password: "password"
    }
  ]
}
```

Where the `key` in `credentials` should correspond to a `key` in `data`. Let me know if you have any suggestions on how to implement this.

**Comment by Yankee-by** [comment]
```
export default {
  collection: "Admin",
  index: "adminProfile.email",
  key: "email",
  data: [
    {
      email: "dev@example.io"
    }
  ],
  credentials: [
    {
      email: "dev@example.io",
      password: "password"
    }
  ]
};
```

@Plazide Am I correct? I cannot make login anyway. 

```
requestRaw: '{"login":{"ref":{"collection":"Admin"},"id":"295858267214578181"},"params":{"object":{"password":"password"}}}',
requestContent: Expr { raw: [Object] },
responseRaw: '{"errors":[{"position":[],"code":"authentication failed","description":"The document was not found or provided password was incorrect."}]}', 
```

```
{
  "ref": Ref(Collection("Admin"), "295858267214578181"),
  "ts": 1618411280807000,
  "data": {
    "email": "dev@example.io"
  }
}
```

**Comment by Plazide** [comment]
Hey, sorry! I wasn't clear enough.

What you want to do is NOT currently supported. The code I posted is just a suggestion on how it would look if it was implemented.

As I said, I can see this being useful so I will definitely implement it. I'll leave a comment on this issue when it's done.

Sorry for the confusion.

**Comment by Vadorequest** [comment]
Hey @Plazide we also need this feature, is it planned? Is there any ETA? How could we help?

**Comment by Plazide** [comment]
Hey @Vadorequest,

It is planned, but I don't have an ETA. Haven't had a lot of time to work on this lately, but will hopefully be able to start later this week. If you have any suggestions regarding the implementation, improvements to the example above or something completely different, that would help a lot.

**Comment by Vadorequest** [comment]
The goal is to define passwords for admin users and use those data as seed, so it's consistent and automated across all our databases.

The above specifications seems clear enough for me, I don't really have anything to add regarding the API you described, it seems to do the job well and is simple to understand.

**Comment by Plazide** [comment]
Hey @Vadorequest and @Yankee-by 

A new version has been published to NPM which allows you to add credentials in the manner shown above!

Let me know if you have any issues!
