### ISSUE TITLE
Cannot resolve graphql and codegen plugin packages in monorepo when using codegen

### ISSUE THREAD

**Issue by winghouchan** [Plazide/fauna-gql-upload#40]
Given the following repository setup:

```
root/
├─ node_modules/
│  ├─ fauna-gql-upload/
│  ├─ graphql/
├─ packages/
│  ├─ another-package/
│  ├─ database/ 📍
│  │  ├─ node_modules/
│  │  │  ├─ .bin/
│  │  │  │  ├─ fgu ↪
│  │  ├─ .fauna.json
├─ package.json
```

and the current working directory being `root/packages/database`, when `fgu --codegen` is run the following error is thrown:

```
Error: Cannot find module 'root/packages/database/node_modules/graphql'
```

This is because the GraphQL package is resolved as follows: https://github.com/Plazide/fauna-gql-upload/blob/b5fb6d3392ba2aa49f158ca81692d564501bb222/src/lib/codegen.ts#L23

The assumption that the GraphQL package exists in the `node_modules` directory within the current working directory doesn't hold up in monorepo setups where the package would be installed in the root `node_modules` directory.

**Comment by winghouchan** [comment]
I think it is possible to just do `import("graphql")`, according to the [resolver algorithm](https://nodejs.org/api/esm.html#resolver-algorithm-specification) it should work.

**Comment by winghouchan** [comment]
Codegen plugins are also affected: https://github.com/Plazide/fauna-gql-upload/blob/b5fb6d3392ba2aa49f158ca81692d564501bb222/src/lib/codegen.ts#L98

**Comment by Plazide** [comment]
Yeah, I was having problems with importing graphql when implementing codegen. Seemed to me like this was the best solution, but I'll have to reconsider.

You seem to be correct in that `import("graphql")` would work. I am testing to see if it works as intended. Will release a patch when fixed.

**Comment by Plazide** [comment]
We now simply use `import(...)` to load both graphql and any potential plugins. Check out version `2.4.1` to try it out.

Let me know if it works for you!

**Comment by winghouchan** [comment]
It works! Thanks for the speedy resolution 😄
