### ISSUE TITLE
Field should not be required in index terms

### ISSUE THREAD

**Issue by employee451** [Plazide/fauna-gql-upload#43]
Hi, the `field` property in the `IndexTerm` interface shouldn't be required, since you can have index terms without using fields (i.e. only using bindings). Great library btw!

**Comment by Plazide** [comment]
Yes, you are correct. That is a mistake on my part. I'll release a patch soon.

**Comment by Plazide** [comment]
Sorry for the wait, I took the opportunity to improve the types in general. There were some more issues that should be addressed now.
