### ISSUE TITLE
Add support for domain data

### ISSUE THREAD

**Issue by goldenshun** [Plazide/fauna-gql-upload#8]
One thing that I love about this project is how easy it is to recreate my FaunaDB database. In one command, I can generate the GraphQL schema and supporting functions, indexes and roles.

One missing piece for me is domain data, data that I add as the developer that is required for the operation of the application. I think it would be helpful to add support for a `/data` directory where one could drop files similar to the ones under `/functions`, `/roles`, etc. and declare data that gets upserted into FaunaDB when running `fauna-gql-upload`.

I could put a PR together if this sounds like a good fit.

**Comment by Plazide** [comment]
That is a great idea! It is something I have thought about adding, but haven't gotten around to.

So, it would be awesome if you could put together a PR!

Also, sorry for the late response. It seems I'm not getting notifications for new issues.

**Comment by goldenshun** [comment]
@Plazide I just opened a PR, let me know what you think!

https://github.com/Plazide/fauna-gql-upload/pull/9

**Comment by goldenshun** [comment]
Released with version 1.8.0
